---
version: '3.8'
networks:
  web:
services:
  nginx:
    build: ./nginx
    depends_on:
      - phpfpm
    volumes:
      - ./www:/usr/share/nginx/html:ro
    networks:
      - web
    ports:
      - "80:80"
  phpfpm:
    build: ./php-fpm
    volumes:
      - ./www:/var/www/html
    networks:
      - web
    ports:
      - "9000:9000"
